### ISSUE TITLE
Update for gsl 1.14

### ISSUE THREAD

**Issue by ghost** [clbustos/statsample-optimization#1]
When I install statsample-optimization with bundler, it depends on an older version of gsl that is incompatible:

  Bundler could not find compatible versions for gem "gsl":
    In Gemfile:
      statsample-optimization depends on
        gsl (~> 1.12.109)

Could you consider updating statsample-optimization? I would be happy to donate $20 toward this. Thanks for your work on it.

Cheers, Joel

**Comment by clbustos** [comment]
No problem. Do you need the standard native gem or the windows one?

On Sat, Sep 10, 2011 at 12:39 AM, SixArm <
reply@reply.github.com>wrote:

> When I install statsample-optimization with bundler, it depends on an older
> version of gsl that is incompatible:
> 
>  Bundler could not find compatible versions for gem "gsl":
>    In Gemfile:
>      statsample-optimization depends on
>        gsl (~> 1.12.109)
> 
> Could you consider updating statsample-optimization? I would be happy to
> donate $20 toward this. Thanks for your work on it.
> 
> Cheers, Joel
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/clbustos/statsample-optimization/issues/1

## 

Claudio Bustos
Psiclogo
clbustos@gmail.com

**Comment by SixArm** [comment]
Thank you...  native please. In case it's relevant, I'm using the gem gsl (1.14.7), Ubuntu 11, Red Hat 6.

Much obliged!

**Comment by clbustos** [comment]
SixArm:

No problem at all.
If you wanna donate, great, but don't feel obligated.

On Sat, Sep 10, 2011 at 2:56 AM, SixArm <
reply@reply.github.com>wrote:

> Thank you...  native please. In case it's relevant, I'm using the gem gsl
> (1.14.7), Ubuntu 11, Red Hat 6.
> 
> Much obliged!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/clbustos/statsample-optimization/issues/1#issuecomment-2058076

## 

Claudio Bustos
Psiclogo
clbustos@gmail.com

**Comment by SixArm** [comment]
Happy to donate. Do you have a donate button anywhere or a PayPal, WePay, etc.? My direct email is joel@sixarm.com

**Comment by clbustos** [comment]
It was already updated on December (Sorry, I didn't remember)
See: https://rubygems.org/gems/statsample-optimization

Use "bundle update". I tested statsample against gsl-1.14 and works fine.
