### ISSUE TITLE
upgrade statsample dependency from 0.17 to 1.2

### ISSUE THREAD

**Issue by maia** [clbustos/statsample-optimization#2]
The statsample dependency is still set to ~>0.17, which locks in 0.18 instead of the current 1.2 when using it in bundler. Could you update it, as now one has to choose between using the latest statsample or using the older API but with GSL support. Thanks.

**Comment by clbustos** [comment]
Done.

**Comment by maia** [comment]
thanks a lot for the quick fix!

**Comment by clbustos** [comment]
He, no problem. Anything you want, just raise an issue
